### ISSUE TITLE
Select and port features upstream

### ISSUE THREAD

**Issue by thomassth** [M2Team/NanaZip#1]
New context menus comes to mind. But other UI improvements might not bode well if 7zip puts more emphasis to smaller package or backward comparability.

**Comment by MouriNaruto** [comment]
It's my pleasure if some features in this project can be merged in the 7-Zip mainline. But the 7-Zip mainline is not use Git, SVN or similar tool to manage the source code. I really don't know how to provide pull request directly and get the reply from him as soon as possible because I don't like waiting for replying and it makes me very sad. 

I had a really terrible pull request experience (I had 0 replies for a PR from a indirecly commiter until waiting for several days, months or years, but finally they had merged it because guys from Mozilla really want the feature I committed.) in OpenSSL project several years ago, and I am afraid that I will have that experience again. So this is why I don't want to commit to other open source project anymore except the repository owner want me to be the maintainer, and I put most efforts on open source projects created by myself.

This is why I create this project and made the old codebase from 7-Zip mainline and new implementation made by this project separately. I hope it will help the author of 7-Zip to port features easier. It's a similar way like 7-Zip ZS because I provide the proof of concept and wait the author to port it if he really think it is useful.


> But other UI improvements might not bode well if 7zip puts more emphasis to smaller package or backward comparability.

I wonder to provide another flavor because I know many people really want a archiver with modern Windows interface. For example, at least you can know that in https://sourceforge.net/p/sevenzip/feature-requests/1536.


I hope these reply can make you some help.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I think it's time for close the issue because this issue have no further responses.

Kenji Mouri

**Comment by Neustradamus** [comment]
@all: It is linked to:
- https://sourceforge.net/p/sevenzip/feature-requests/1028/
- https://sourceforge.net/p/sevenzip/feature-requests/1169/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/6307c6fd/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/7a122fc2/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/fa951551/

Please comments on it...

**Comment by Neustradamus** [comment]
@ all: It is linked to:
- https://sourceforge.net/p/sevenzip/feature-requests/1028/
- https://sourceforge.net/p/sevenzip/feature-requests/1169/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/6307c6fd/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/7a122fc2/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/fa951551/

Please comments on it...
