### ISSUE TITLE
Few issues with new context menu

### ISSUE THREAD

**Issue by shiroshan** [M2Team/NanaZip#10]
Noticed a few weird behaviors in the new context menus. I don't know if some are just limitations of the new system, but I still wanted to report them just in case.

1. Category separators are displayed at the end of list even if there aren't any more categories
![image](https://user-images.githubusercontent.com/18249551/135875211-a3ade9a2-d78a-4bf5-9973-ad41a6a57dce.png)

2. When only 1 menu item enabled, it is still being indented into a submenu, it would be better to just display it as is, or to be put as an option (like in original 7zip).
![Untitled-2](https://user-images.githubusercontent.com/18249551/135875639-f25dfcc2-4873-4124-bf3c-054c8b9da661.png)

3. When no options that could interact with folders are enabled (such as Add to, Compress and CRC SHA), app still displays in folder context menu, resulting in empty entry that doesn't do anything.
![image](https://user-images.githubusercontent.com/18249551/135877936-0c7c5f1d-b347-4224-9121-05dc9050c8d7.png)

It would be great if you could fix these issues. Thanks to the team for your work on this project.

**Comment by MouriNaruto** [comment]
The new context menu still need to polish.

I will try to fix these issues in 1.0 Preview 3.

Kenji Mouri

**Comment by shiroshan** [comment]
Thanks for the fixes.

> I can't do that because NanaZip uses the parent context menu item for registering to Windows AppX manifest and initialization.

I believe it should be technically possible to do this, since WinRAR has this exact feature implemented. Unless, of course, it's a limitation that comes from being a packaged app. 
![1](https://user-images.githubusercontent.com/18249551/136623056-e84308f8-e997-492b-a499-59d94c4bdb36.png)
![2](https://user-images.githubusercontent.com/18249551/136623062-9417117b-a8cb-4ce1-ba49-20776471bb3c.png)

If it really can't be implemented in this project though, I think this issue can be closed, as everything else was fixed.

**Comment by MouriNaruto** [comment]
@shiroshan 

The context menu implementation for NanaZip doesn't support cascading mode because I want to provide a universal experience when users using the new context menu and old context menu. 

Also I don't want to register a plenty of context menu handlers which are only displaying one item for the specific format because of the performance, and NanaZip uses the parent context menu item to accelerate the speed for invoking the child context menu item.

So I hope you can understand my choice. And I will close the issue. Thank you very much,

Kenji Mouri
