### ISSUE TITLE
Toolbar buttons have grey background when hovered

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#103]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

As in the title:
![image](https://user-images.githubusercontent.com/39709348/149845352-29d6481f-845f-476d-82a1-44c5777e4015.png)

Used version: NanaZip 1.0 x64

**Comment by MouriNaruto** [comment]
Thank you very much for reporting this.

This is the known issue because Win32 toolbar control don't support true transparent icons. I will solve it by rewriting the NanaZip UI with Windows Runtime XAML, and the plan is on the development roadmap of NanaZip 2.x Series.

Stay tuned for this!

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- Duplicate: #55

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #55 to get further information and discuss with us there.
