### ISSUE TITLE
DPI Aware

### ISSUE THREAD

**Issue by FayneAldan** [M2Team/NanaZip#112]
It would be nice if NanaZip was DPI aware.

![](https://files.catbox.moe/yr0ttz.png)

The only real problems are the Up button and default column sizes are too small.

**Comment by HubKing** [comment]
I had the same problem (small UP button) with the original 7ZIP. I used to use forced-DPI scaling (Compatibility -> Override DPI -> System (Enhanced)). I also had small file entry text with 7ZIP. NanaZip looks marginally better but I am not sure why the things have to be like this.

What I would to see are:

* Ability to change menu font size. In case it is using old Win32 native menu that the font size cannot be changed, can't it be upgraded to Windows 11's menu? I mean, it looks a lot easier to read than old Win32's menus.
![image](https://user-images.githubusercontent.com/10900489/153096020-0befc9be-8e19-43a3-9350-0d4c3f6dcacd.png)

* Ability to change menu toolbar button sizes. If that is too much, just adding some text like "Go up" to the up arrow to make the button wider so that it would be easy to click.

* Ability to change dialogue font size. It is pain in the arse that so many Win32 apps have tiny dialogue font size like this. I would like the font to be at least as big as that of the Window's settings window.

![image](https://user-images.githubusercontent.com/10900489/153096274-570ff9c7-0961-4dff-960a-469e7c313111.png)

**Comment by SakuraNeko** [comment]
Because of our limited time and effort, we will not be fixing these issues again in version 1.x.
We will plan to refactor the modern user interface in version 2.0, and these issues will be fixed then.
We hope you will wait a little while.

**Comment by SakuraNeko** [comment]
@FayneAldan We will be working on some DPI support preparations in the near future, and you can see this on our commits (d8144c2 , 04d2281). When they do work, we'll let you know here.
We look forward to your verification at that time.

**Comment by MouriNaruto** [comment]
@FayneAldan @SakuraNeko 

NanaZip 1.1 Servicing Update 1 Preview 2 (1.1.201.0) is submitted to Microsoft Store three days ago and waiting for verification.

https://github.com/M2Team/NanaZip/blob/master/Documents/ReleaseNotesPreview.md

I will close this issue when verification is passed.

Kenji Mouri

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NanaZip/releases/tag/1.1%2BServicingUpdate1-Preview2

NanaZip 1.1 Servicing Update 1 Preview 2 (1.1.201.0) is released and solved this issue. So, it's time to close the issue.

Kenji Mouri

**Comment by SakuraNeko** [comment]
In the Task Manager, we can see that the preview version of NanaZip has started working as scheduled.
![image](https://user-images.githubusercontent.com/22462516/159839152-f44162a7-214e-4fce-8ec0-77de7589710e.png)
