### ISSUE TITLE
Another software crashes when opening NanaZip context menu

### ISSUE THREAD

**Issue by No5972** [M2Team/NanaZip#113]
The another software is "Everything".

Steps to reproduce the issue:
1. Open an Everything search window
2. Right click a archive file
3. Hover over "NanaZip" option
4. "Everything" crashes. The search window directly disappears. 
5. It does not crash every time. Sometimes it behaves to be not displaying the sub menu.

![](https://img-blog.csdnimg.cn/b7b9b1c4b8a742e89d66ebc0104ea35f.png)

Environment:
* Windows 10 Pro 21H2 19044.1466
* NanaZip 1.0 (x64)
* Everything V1.4.1.1005 (x64)

---

EDIT 01/29/2022:
Same issue in Windows 11, too.

Environment:
* Windows 11 Home 21H2 22000.438
* NanaZip 1.0 (x64)
* Everything V1.4.1.969 (x64)

![](https://img-blog.csdnimg.cn/8813acf56a714386aa109378936fa5c8.png)

**Comment by SakuraNeko** [comment]
We need more details.
We are not sure if the cause of the issue is on NanaZip and suggest to report the issue to the development team of everything as well.

Sakura

**Comment by MouriNaruto** [comment]
It looks like the Everything may not support the out of process shell extensions. But the shell extension from the application which packaged by the desktop bridge need to run out of process.

And the app called Files supports NanaZip: https://github.com/M2Team/NanaZip/issues/2. Maybe you should feedback your suggestion to the develop team of Everything.

The issue is as similar as https://github.com/M2Team/NanaZip/issues/21.

Kenji Mouri
