### ISSUE TITLE
在windows11 22000.588上出现右键菜单撕裂和对非压缩文件右键依然出现nanazip的菜单的问题

### ISSUE THREAD

**Issue by VoidxHoshi** [M2Team/NanaZip#124]
![image1](https://user-images.githubusercontent.com/55886143/158790643-87d4a31a-c3ac-4db8-b052-44640f0a72ec.png)
![image2](https://user-images.githubusercontent.com/55886143/158790736-c1220507-579c-4c95-b4d3-7ee6ad9db2f1.png)

**Comment by MouriNaruto** [comment]
撕裂是 Windows 11 的已知问题（这个你需要向微软进行反馈）
非压缩文件显示 NanaZip 菜单属于特性（方便用户以 NanaZip 支持的方式查看各类文件的内容）

毛利

**Comment by SakuraNeko** [comment]
我们**怀疑**可能是微软的新版右键菜单模块（Windows 11）在处理较长的应用名称时会出现错误宽度计算导致了这个问题。
因为预览版本的NanaZip和正式版在菜单部分的其他逻辑并无不同，但正式版中该问题无法复现。

**Comment by AndromedaMelody** [comment]
This issue doesn't belong to NanaZip, which other applications have the same trouble. Microsoft seems to have been fixed it in Windows 11 22H2 (Build 22621). If the problem is found to appear again in the **latest** Windows, you can reopen(and comment) this issue or submit an new issue (remember note the complete Windwos Version Number). Thanks for your support.
