### ISSUE TITLE
NanaZip does not show context menu in desktop

### ISSUE THREAD

**Issue by gabri25ele** [M2Team/NanaZip#137]
same file in Windows 11 (22000.593)
in another place context menu has nanazip
![000001](https://user-images.githubusercontent.com/33927879/160615345-0918cdab-7035-4168-9705-c6c04a718575.png)

in Desktop context menu has not nanazip
![000002](https://user-images.githubusercontent.com/33927879/160615393-8f7debbd-85f4-4a29-961c-74933f2248c6.jpg)

**Comment by MouriNaruto** [comment]
I can't reproduce the issue.

I think you should read the [known issues](https://github.com/M2Team/NanaZip#known-issues) first, some issues do not belong to NanaZip.

Kenji Mouri

**Comment by octopushugger** [comment]
> I think you should read the [known issues](https://github.com/M2Team/NanaZip#known-issues) first, some issues do not belong to NanaZip.

Thanks for that. The restart explorer issue should also be listed on the releases page so people don't have to dig into the readme or issues.

**Comment by AndromedaMelody** [comment]
- Duplicate #35 

- NanaZip have improved to integrate with File Explorer in #205 , and Maybe it is also valid for modern context menu.

Dose Windows Terminal have the same trouble? Microsoft may fix it in Windows 11 22H2 (Build 22621).
No new feedback(or the new duplicate issue) for a long time, so we will close this issue as completed. If the problem is found to appear again in the **latest** Windows, you can reopen(and comment) this issue or submit an new issue (note the complete Windwos Version Number). Thanks for your support.
