### ISSUE TITLE
Add NanaZip to winget

### ISSUE THREAD

**Issue by Void48** [M2Team/NanaZip#14]

**Comment by MouriNaruto** [comment]
Reference: https://github.com/M2Team/NanaZip/issues/7#issuecomment-932697999

The winget is able to install Windows Store apps via command line in the current stage. So I only need to distributed to Windows Store and provide MSIX package with self signature to GitHub.

We need to waiting Microsoft to polish their infrastructures which supports unpackaged mode for XAML Islands apps. And it can make me to make unpackaged version and try to publish to more package managers.

I think it's time for closing the issue because I have explained it before.

Kenji Mouri
