### ISSUE TITLE
Is NanaZip abandoned?

### ISSUE THREAD

**Issue by Spontini** [M2Team/NanaZip#201]
Is it abandoned? There are no updates released in the near past.

**Comment by MouriNaruto** [comment]
Hi, I am the author of NanaZip. Also I am the only one active maintainer of NanaZip in most cases.

First, NanaZip is still developing new features. You will know that in the source code repository commit list.

I am also do some work about the XAML Islands based UI stack by developing other Nana Series projects. Because NanaZip is the critical project for many people including me. I don't think people can bear the reset of the development progress like Windows Longhorn. So I need to develop some other projects to validate things will be used in NanaZip.

Due to the reality, NanaZip can only promise 1 release (including preview) per year.

Kenji Mouri

**Comment by Shomnipotence** [comment]
No，it develops by Mori normally.

**Comment by fluentmoheshwar** [comment]
> Hi, I am the author of NanaZip. Also I am the only one active maintainer of NanaZip in most cases.
> 
> First, NanaZip is still developing new features. You will know that in the source code repository commit list.
> 
> I am also do some work about the XAML Islands based UI stack by developing other Nana Series projects. Because NanaZip is the critical project for many people including me. I don't think people can bear the reset of the development progress like Windows Longhorn. So I need to develop some other projects to validate things will be used in NanaZip.
> 
> Due to the reality, NanaZip can only promise one release (including preview) per year.
> 
> Kenji Mouri

Since you answered the question close the issue.
