### ISSUE TITLE
Installation for All Users?

### ISSUE THREAD

**Issue by Wolverine1977** [M2Team/NanaZip#217]
If this is documented somewhere -apologies, I searched the website and couldn't see anything. Is there a way NanaZip can be installed for all users on a system?
e.g. 7-zip, WinRAR etc. when installed are available for any user that logs on to a system, NanaZip appears to be user or profile specific?
Is this possible or is this how all .msixbundle files are designed to work?
Thanks for reading.

**Comment by MouriNaruto** [comment]
Maybe it will be helpful.

https://learn.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.provisionpackageforallusersasync?view=winrt-22621#windows-management-deployment-packagemanager-provisionpackageforallusersasync(system-string)

Kenji Mouri

**Comment by AndromedaMelody** [comment]
You can execute this command in PowerShell:
`Add-AppxProvisionedPackage -Online -PackagePath <The path of the MSIX package> -SkipLicense` 
or this command in CMD or PowerShell:
`DISM.exe /Online /Add-ProvisionedAppxPackage /PackagePath:<The path of the MSIX package> /SkipLicense`

More custom options you can find in [PWSH Doc](https://learn.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=windowsserver2022-ps) and [DISM Doc](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-app-package--appx-or-appxbundle--servicing-command-line-options?view=windows-11)

Tip: Due to the police from Microsoft Store, if you offline install, First running NanaZip must connect to the Internet to get License, otherwise Windows will prevent to open NanaZip.

Thanks for your support, NanaZip 2.x will provide installer for simplify the deployment , which uses the WinRT API mentioned by Kenji Mouri.

**Comment by Wolverine1977** [comment]
Thanks for the responses - Any chance this option could be incorporated into the final Installer or option menu to select - Install for this user only / All users?

**Comment by RayGicEFL** [comment]
The Installer is a great work and is still far from us. However, I don't think there is any installer without options to install for all users if it could do so.

**Comment by AndromedaMelody** [comment]
Fix: 29ce870d16a9419d2d64a21583a164442cbb89b2

About EXE Installer:
We hope you subscribe #169 to get further information and discuss there.
  > - <sup>Original posted by @MouriNaruto in https://github.com/M2Team/NanaZip/pull/209#issuecomment-1236202127 at 2022-09-03T21:38:54Z</sup>
  > NanaZip will provide exe installer (You can see the empty reversed NanaZipInstaller project in the current stage.) after NanaZip is modernized by XAML Islands.
  > Kenji Mouri

As a result, we will close this issue as completed.
