### ISSUE TITLE
Translation PT BR

### ISSUE THREAD

**Issue by maisondasilva** [M2Team/NanaZip#221]
Where can I help to translate some places I see in English yet?

![image](https://user-images.githubusercontent.com/11423362/193687008-660eb241-4903-45cd-af5b-c393840523ea.png)

![image](https://user-images.githubusercontent.com/11423362/193686915-eb0c1a41-83e2-4419-86dc-9b9b4c4d839e.png)

**Comment by RayGicEFL** [comment]
Please wait for nanazip to be modernized with xaml. Then, the ways to localize will also changed to using resw files. So after modernization, all fixes to legacy localization would be "re-applied" to new one, which means we don't have to fix localization problems at now (just my opinion).

**Comment by AndromedaMelody** [comment]
NanaZip has been using MRT(.resw files) since [NanaZip 1.2 Preview 3](https://github.com/M2Team/NanaZip/releases/tag/1.1%2BServicingUpdate1-Preview3). But it is generated from legacy localization texts by [a automatic tool](https://github.com/ProjectMile/Mile.Net). So if we change localization texts now, it is possible to break the current tool-chain. Also it means we need do more meaningless things when modernizing NanaZip with XAML, because we need regroup localization texts and using x:Uid to banding the translated text.

**Comment by maisondasilva** [comment]
No problem, you can count on me when you need

**Comment by maisondasilva** [comment]
@MouriNaruto  I think we can close this with the pull that I sent out of correct translation? 

https://github.com/M2Team/NanaZip/pull/444#event-13022500711
