### ISSUE TITLE
Starting Nanazip doesn't open app/explorer window

### ISSUE THREAD

**Issue by z3llu** [M2Team/NanaZip#231]
Hi, I have some strange bug. 
I have Nanazip from Windows store, it added itself to the context menu and it works just fine using context menu options.
However, when I doubleclick archive or try to open Nanazip.exe... nothing happens. I got circle cursor for a moment and nothing happens. I don't have any 'explorer-like' window. 

I've reinstalled Nanazip, even cleaned a little of registry. Still nothing.

**Comment by MouriNaruto** [comment]
First, I wonder to know that can your environment run Windows Terminal properly?

Or you have installed something like MacType?

Kenji Mouri

**Comment by z3llu** [comment]
Hi Kenji!
That's my private computer, no strange IT guys involved ;) Yeah, my cmd and powershell are working fine (I guess that's what you meant by Windows Terminal). If you need me to run some specific command, feel free.

From the things altering (I guess) explorer I have puretext, powertoys, taskbarX and (I don't know what it is in particular) some ViVe addon to enable windows explorer tabs (I have Win 11 22H2, but this problem was present before the update and installing ViVe).

I've restarted into safe mode and still Nanazip won't popup, when I tried "open using..." on any .zip file, I've got windows notification that it cannot find the proper filter - or something like this, I don't have english windows version.

**Comment by RubenPX** [comment]
Same here

**Comment by dinhngtu** [comment]
Windows Terminal: https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701

Do you have any events in Event Viewer's Application log indicating a problem with NanaZip?

**Comment by helpimnotdrowning** [comment]
This is also happening to me. When trying to launch NanaZip (installed from winget and msstore) either through opening a file or through the shortcut, nothing happens. There are 2 events in the Event Viewer created every time I launch NanaZip:
![image](https://user-images.githubusercontent.com/35247379/201239507-11d28c2d-d4c0-4af8-b8b8-27b8def994e1.png)
![image](https://user-images.githubusercontent.com/35247379/201239517-ba6708c0-661b-4201-a22a-6dd2d2f026ef.png)
This *seems* like it could be an incompatibility with [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher), but this could be showing up because it loads into the Explorer directly (at least I think, I don't know how ExplorerPatcher works internally) and just so happens to show up in the stack trace .

**Comment by helpimnotdrowning** [comment]
Quickly flicking through some settings, the problem is indeed ExplorerPatcher. Enabling the option `File Explorer > Register as shell extension` stops NanaZip from opening. Disabling it restores functionality instantly, no restarts needed.

**Comment by dinhngtu** [comment]
Interesting. Do you have the "Show system menu" option enabled in NanaZip settings?

**Comment by helpimnotdrowning** [comment]
It doesn't make a difference whether it's on or off.

**Comment by z3llu** [comment]
I can confirm that this option indeed prevents nanazip from starting. I've reinstalled my OS and everything was working well, but after turning on "register as shell extension" NanaZip doesn't start up.
