### ISSUE TITLE
NanaZip winget package is outdated

### ISSUE THREAD

**Issue by ShayBox** [M2Team/NanaZip#232]
The non-windows-store NanaZip winget packages are outdated and giving me this error message.  
Installing the updated msix bundle manually fixed it, but can someone update the non-store packages?  
Store apps have issues with file permissions causing overlaying, that gets reverted when uninstalling the app.  
![image](https://user-images.githubusercontent.com/9505196/198716997-7b3b749e-2dd3-47f5-bea9-89f1139cc63d.png)

**Comment by AndromedaMelody** [comment]
NanaZip in WinGet is driven by unofficial community and Microsoft Store.

> Unofficial community: `winget search M2Team.NanaZip`
In Oct 12, 2022, it has provided NanaZip Stable 2.0. https://github.com/microsoft/winget-pkgs/pull/83191 & https://github.com/microsoft/winget-pkgs/pull/83192

>Microsoft Store: `winget search 9N8G7TSCL18R` & `winget search 9NZL0LRP1BNL`
It provides the latest version once NanaZip certificated by MS-Store Team.

Thanks for your support.

**Comment by AndromedaMelody** [comment]
@stevensko , @SakuraNeko discussed in https://github.com/M2Team/NanaZip/discussions/238

Convert discussion(#238) to here, please read #274. Thank you.

---

<div type='discussions-op-text'>

<sup>Originally posted by **@stevensko** November 14, 2022</sup>
## Windows Store version
Are you going to update the windows store preview version? winget is trying to install the stable release because the preview is out of date

</div>

---

<div type='discussions-op-text'>

<sup>Originally posted by **@SakuraNeko** December 11, 2022</sup>
We will update the preview version along with the official version of the store to avoid this problem from happening again. In addition, you can refer to our [release page](https://github.com/M2Team/NanaZip/releases) to see how we resolve the issue.

</div>
