### ISSUE TITLE
Feature Request: direct menu entries (without Submenu) [productivity enhancement]

### ISSUE THREAD

**Issue by maxwowpow** [M2Team/NanaZip#244]
As the entries on the top level, there should be selected items directly there, without "NanaZip" subfolder.

![image](https://user-images.githubusercontent.com/169885/204062065-26eb3f1b-b6e1-4b35-a170-fe5abce4eb17.png)

All menu items selected will be shown on the root level, if the 7-zip option `cascade` is unselected:

![image](https://user-images.githubusercontent.com/169885/204062155-0c2d23f8-5160-4020-92e6-892f44701fce.png)

PS: Huge thanks to all the contributors. This feature saves 1 menu open time and with often usage that sums to a lifetime!

**Comment by Shomnipotence** [comment]
An app has only one item in this menu.  @MouriNaruto Will you close it?

**Comment by MouriNaruto** [comment]
@maxwowpow 

According to https://blogs.windows.com/windowsdeveloper/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11, we know "Apps with more than 1 verb are grouped into a flyout with app attribution".

So, we can't do that if we want to make users install NanaZip properly via Microsoft Store.

I also see your screenshots. It's two app. (One provides "App example with 1 verb", another provides "App example with many verbs".)

Kenji Mouri

**Comment by Shomnipotence** [comment]
@maxwowpow 
The reason why Microsoft forces menus with more than one item to be placed in the menu group is because too many applications added several items to the first-level menu, which caused the first-level menu to be too long and have too many items.

So we decided to follow Microsoft's rule

If you approve:
Users have the right to decide which menu items are fixed in the first-level menu.
Please provide feedback to Microsoft.
