### ISSUE TITLE
Why dark mode taking so long to implement? Can we have an early access for it?

### ISSUE THREAD

**Issue by bigplayer-ai** [M2Team/NanaZip#270]
Hey,
Why dark mode taking so long to implement? Can we have an early access for it?

**Comment by MouriNaruto** [comment]
In recent days, some people ask me why not working on NanaZip regularly. Here is why.

Maybe you need to know I am not a full-time or paid developer for NanaZip. I have my work to do. I need to work for Tencent-related company during the day. I develop individual open-source projects at night.

I also need to port the project (I am a leader of a live-streaming project for Windows) which I maintained for the company to Linux in recent days. So, I am really busy. I sleep in midnight every day because I need to do both company project and individual projects. I hope I can have more sponsors and contributors for encouraging me not to give up. (I am afraid I would give up without the AndromedaMelody's huge contributions for Mile.Xaml and NanaZip.)

Here is the way to sponsor me: https://github.com/mourinaruto#sponsor-service

Kenji Mouri

**Comment by shikkoku** [comment]
> 

噫，你在腾讯上班啊，难怪。

**Comment by MouriNaruto** [comment]
@shikkoku 

> 噫，你在腾讯上班啊，难怪。

只是下面的子公司而已

毛利

**Comment by shikkoku** [comment]
> @shikkoku
> 
> > 噫，你在腾讯上班啊，难怪。
> 
> 只是下面的子公司而已，所以我写的是 Tencent-related company
> 
> 毛利

保重身体，腾讯系的干活辛苦。

**Comment by AndromedaMelody** [comment]
- Duplicate: #8 

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #8 to get further information and discuss this issue with us there.
