### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by kittenvr** [M2Team/NanaZip#294]
how to activate dark mode

**Comment by MouriNaruto** [comment]
- Help/AboutPage & ContextMenu have supported dark mode. They will follow system settings to change theme automatically.
- `start` not `finish`, we will continue focusing on it.
- For more information, please read #270 .

Thanks for your support.

Kenji Mouri

**Comment by ikoshura** [comment]
I attempted to use the 7Zip Dark Mode created by Huan (https://github.com/huanrenfeng/7zipDarkmode), made minor modifications using Resource Hacker to change both the app icon and toolbar icon, and also to hide the menubar since it couldn't apply the dark mode. Afterward, I replaced the NanaZip.exe file within the NanaZip msixbundle.
![Screenshot 2023-08-28 004821](https://github.com/M2Team/NanaZip/assets/100127946/726ff543-1471-4ca1-a125-f4647f034558)
The end result was that I achieved a 7Zip dark mode appearance, complete with the NanaZip icon and capability to display the menu in the Windows 11 Context Menu.

**Comment by kittenvr** [comment]
> I attempted to use the 7Zip Dark Mode created by Huan (https://github.com/huanrenfeng/7zipDarkmode), made minor modifications using Resource Hacker to change both the app icon and toolbar icon, and also to hide the menubar since it couldn't apply the dark mode. Afterward, I replaced the NanaZip.exe file within the NanaZip msixbundle. ![Screenshot 2023-08-28 004821](https://user-images.githubusercontent.com/100127946/263546266-726ff543-1471-4ca1-a125-f4647f034558.png) The end result was that I achieved a 7Zip dark mode appearance, complete with the NanaZip icon and capability to display the menu in the Windows 11 Context Menu.

ooh

**Comment by ikoshura** [comment]
> ooh

I have uploaded the modified .exe file here: https://github.com/ikoshura/NanaZip-Darkmode. It is also compatible for use with 7Zip.

**Comment by kittenvr** [comment]
> > ooh
> 
> I have uploaded the modified .exe file here: https://github.com/ikoshura/NanaZip-Darkmode. It is also compatible for use with 7Zip.

ok
