### ISSUE TITLE
When select folder and single file in certain order, blank menu is displayed

### ISSUE THREAD

**Issue by lychichem** [M2Team/NanaZip#30]
Example: `foo_uie_eslyric.dll` and folder `Scripts`, which can be downloaded from https://github.com/dream7180/foobox-cn/blob/6.1.x/NSIS%20Source/foobar2000-core/components/foo_uie_eslyric.dll and https://github.com/dream7180/foobox-cn/tree/6.1.x/ESL-Scripts
Steps to reproduce: 
1. Select folder ESL-Scripts (Here I just renamed it to Scripts, which will work same)
2. Then select foo_uie_eslyric.dll by pressing shift or ctrl 
3. Right click on  foo_uie_eslyric.dll
4. A Nanazip menu with nothing in the submenu will show in context menu
![image](https://user-images.githubusercontent.com/9316590/138469264-cb5ea099-7e5a-4b34-9ea2-9b0c2dc7ec52.png)

Note: The issue can just be reproduced strictly according to all the steps above. Changing orders or click on the folder will not cause the issue.
Additional info: 
System: Windows 11 22000.282 x64 Pro zh-CN
NanaZip: 1.0 preview 3
NanaZip context menu setting:
![image](https://user-images.githubusercontent.com/9316590/138469573-77fd3dc4-3e2a-4bd0-a687-3edada3f76c0.png)

**Comment by MouriNaruto** [comment]
I am afraid I can't fix that because it's a bug from Windows 11.

When the default handler is a context menu (some files don't have the default open handler and Windows will set the first item as the default handler), it will show the first item of context menu when you click the blank menu.

In my case, I click the blank menu will show the "Test archives".

![image](https://user-images.githubusercontent.com/10867563/142733533-70aca6e1-629f-46df-9227-2a31d8cba8fc.png)

![image](https://user-images.githubusercontent.com/10867563/142733545-0b2b687f-33d0-445a-b462-5de53666c93b.png)

Kenji Mouri

**Comment by lychichem** [comment]
Understand. Could you please report it to Microsoft? I believe I cannot report the reason of this issue clearly to Microsoft.

**Comment by MouriNaruto** [comment]
@lychichem 

I think Microsoft has been noticed that and fixed the half.

In https://www.reddit.com/r/Windows11/comments/q5lkc0/7zip_is_truly_ahead_of_its_time_explorer_context/, you will see the full context menu instead of the blank menu in the old version of Windows 11.

![image](https://user-images.githubusercontent.com/10867563/142790865-a8004435-3471-42a6-afbd-fab4e53e6456.png)

Kenji Mouri
