### ISSUE TITLE
7-Zip 24.05

### ISSUE THREAD

**Issue by PopuriAO29** [M2Team/NanaZip#401]
7-Zip 24.05 was released!

https://sourceforge.net/p/sevenzip/discussion/45797/thread/b92679e642/

What's new after 24.04 Beta:

* New switch -myv={MMNN} to set decoder compatibility version for 7z archive creating.
{MMNN} is 4-digit number that represents the version of 7-Zip without a dot.
** If -myv={MMNN} switch is specified, 7-Zip will only use compression methods that can be decoded by the specified version {MMNN} of 7-Zip and newer versions.
** If -myv={MMNN} switch is not specified, -myv=2300 is used, and 7-Zip will only use compression methods that can be decoded by 7-Zip 23.00 and newer versions.
* New switch -myfa={FilterID} to allow 7-Zip to use the specified filter method for 7z archive creating.
* New switch -myfd={FilterID} to disallow 7-Zip to use the specified filter method for 7z archive creating.
* Some bugs were fixed.

Last time, I just seen the 7-Zip site, there is now source code.

**Comment by MouriNaruto** [comment]
I'm working on synchronizing the 7-Zip 24.05 source code to NanaZip.Core. You will see related commits in recent days.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have updated 7-Zip to 24.05 for NanaZip.Core.

https://github.com/M2Team/NanaZip/commit/4d21f7251c53ecfe05f16fa1b038ae398349786f

Currently, there are some zstd-related issues for compiling. Due to Igor's implementation only has the decoder. I guess I will use Igor's zstd decoder in sfx stubs for smaller binary size. But for NanaZip.Core.dll, still use full ZS zstd decoder and encoder implementation.

Kenji Mouri

**Comment by MouriNaruto** [comment]
The work of synchronizing the 7-Zip 24.05 source code to NanaZip.Core has finished since https://github.com/M2Team/NanaZip/commit/92ddadb23b48eb2f3ab30291446dd826db036795.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@PopuriAO29

Both NanaZip (Modern) and NanaZip Classic share the same NanaZip Core. So, NanaZip Classic will have 7-Zip 24.05 level codecs.

NanaZip 3.0, which will have the final build in May 27, 2023 (the "Build 1000" is so tasting), won't have the stable version of NanaZip Classic because of the time limit. But I think I will provide portable NanaZip Classic binaries for testing in NanaZip 3.5 Preview 0 after NanaZip 3.0 stable.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Both NanaZip 3.0 and NanaZip 3.5 Preview 0 are released. Read https://github.com/M2Team/NanaZip/releases/tag/3.0.996 for more information.

Kenji Mouri

**Comment by atplsx** [comment]
updated 24.06

**Comment by atplsx** [comment]
updated 24.07

**Comment by MouriNaruto** [comment]
@atplsx The main branch has synchronized to 7-Zip 24.07 mainline.
https://github.com/M2Team/NanaZip/commit/921f6ddfa3807112b92051b8a616208a4c5b64d6

Kenji Mouri

**Comment by atplsx** [comment]
> @atplsx The main branch has synchronized to 7-Zip 24.07 mainline. [921f6dd](https://github.com/M2Team/NanaZip/commit/921f6ddfa3807112b92051b8a616208a4c5b64d6)
> 
> Kenji Mouri

Please release new version 
best regards
