### ISSUE TITLE
Add to chocolatey

### ISSUE THREAD

**Issue by itsmeboy0** [M2Team/NanaZip#45]
7-zip is one of the most downloaded programs in [Chocolatey](https://chocolatey.org/) and it would be good if this was included there as well.

**Comment by MouriNaruto** [comment]
Reference: https://github.com/M2Team/NanaZip/issues/14

I have mentioned we need to waiting Microsoft to polish their infrastructures which supports unpackaged mode for XAML Islands apps. And it can make me to make unpackaged version and try to publish to more package managers.

I think it's time for closing the issue because I have explained it before.

Kenji Mouri

**Comment by oxygen-dioxide** [comment]
@itsmeboy0 
I have added nanazip to choco. 
https://community.chocolatey.org/packages/nanazip.portable
