### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by itsmeboy0** [M2Team/NanaZip#46]
I use 7-zip all in various PCs and so having a portable copy of 7-zip in my USB is quite important. I hope Nanazip would have a portable version as well.

**Comment by MouriNaruto** [comment]
Reference: https://github.com/M2Team/NanaZip/issues/14

I have mentioned we need to waiting Microsoft to polish their infrastructures which supports unpackaged mode for XAML Islands apps. And it can make me to make unpackaged version and try to publish to more package managers.

I think it's time for closing the issue because I have explained it before.

Kenji Mouri

**Comment by TPS** [comment]
#688

**Comment by rollingmoai** [comment]
That seems to be a duplicate of this issue.

> Start to provide the official portable binaries package of NanaZip with both Modern and Classic flavors, **except the NanaZip File Manager.**

Yeah, we also need the portable version "NanaZip File Manager" as well

**Comment by TPS** [comment]
That issue is canonical in that the dev replies re: this there.
