### ISSUE TITLE
Distribution options

### ISSUE THREAD

**Issue by Jogai** [M2Team/NanaZip#7]
A zip program should be distributed as a zip package, if only for the joke of it. Aside from that, its easier to include it in the [scoop](https://github.com/lukesampson/scoop) repo's, which is my preferred method of installation.

**Comment by MouriNaruto** [comment]
The current development stage of NanaZip is packaged version only. So we don't distribute zip/7z package unless NanaZip add the unpackage mode support.

**Comment by lychichem** [comment]
> A zip program should be distributed as a zip package, if only for the joke of it. Aside from that, its easier to include it in the [scoop](https://github.com/lukesampson/scoop) repo's, which is my preferred method of installation.

Can Scoop distribute packages from Microsoft store? As far as I know, Winget can distribute package from MS Store. For now, You can give Winget a try, and wait for NanaZip adding the unpackage mode support

**Comment by SakuraNeko** [comment]
@lychichem 
Thank you very much for your suggestion.

We will probably upload this software to the winget repository in the near future, but until then we want our software to be more stable.

SakuraNeko

October 2, 2021

**Comment by Jogai** [comment]
> For now, You can give Winget a try, and wait for NanaZip adding the unpackage mode support

I rather not use a tool that was obtained by tricking the original developer, taking open source work, rebranding it, and released with less than half the feature set that is supposed to go into a package manager.

That said, for the sake of this discussion, I think winget will be able to install store apps, so to enable winget distribution maybe a store listing will be enough.

**Comment by MouriNaruto** [comment]
@Jogai 

> I rather not use a tool that was obtained by tricking the original developer, taking open source work, rebranding it, and released with less than half the feature set that is supposed to go into a package manager.

If you really need a project which released with more than half the feature set at the early time, you should choose the projects which have a large company to maintain. (NanaZip is more like a personal project because I am the only source code maintainer. They can create a PR to me if they want to do some changes.)

I don't think NanaZip is a project which tricking the original developer, taking the open source work and rebranding it. Because it's full open source, have a long roadmap to achieve and everyone knows it's a 7-Zip derivative, especially a Japanese and they will get the pun.

> I think winget will be able to install store apps, so to enable winget distribution maybe a store listing will be enough.

And winget is able to install Windows Store apps via command line in the current stage. So I only need to distributed to Windows Store and provide MSIX package with self signature to GitHub.

I think it's time for closing the issue because we need to waiting Microsoft to polish their infrastructures which supports unpackaged mode for XAML Islands apps.

Kenji Mouri

**Comment by lychichem** [comment]
> @Jogai
> 
> > I rather not use a tool that was obtained by tricking the original developer, taking open source work, rebranding it, and released with less than half the feature set that is supposed to go into a package manager.
> 
> If you really need a project which released with more than half the feature set at the early time, you should choose the projects which have a large company to maintain. (NanaZip is more like a personal project because I am the only source code maintainer. They can create a PR to me if they want to do some changes.)
> 
> I don't think NanaZip is a project which tricking the original developer, taking the open source work and rebranding it. Because it's full open source, have a long roadmap to achieve and everyone knows it's a 7-Zip derivative, especially a Japanese and they will get the pun.
> 
> > I think winget will be able to install store apps, so to enable winget distribution maybe a store listing will be enough.
> 
> And winget is able to install Windows Store apps via command line in the current stage. So I only need to distributed to Windows Store and provide MSIX package with self signature to GitHub.
> 
> I think it's time for closing the issue because we need to waiting Microsoft to polish their infrastructures which supports unpackaged mode for XAML Islands apps.
> 
> Kenji Mouri
His opinion is not for your program. It's for winget. Actually, I have to say Winget is not clean. It DID tricked the original developer and have less function compared to chocolatary or scoope. But Microsoft are continuslly adding new functions.
Anyway, if you don't like something, you can choose not using it, it's your freedom.

**Comment by MouriNaruto** [comment]
@lychichem 

> His opinion is not for your program. It's for winget.

But I still need to clearify about the NanaZip because I don't want other people to doubt my conduct.

I hope my words can be understood.

Kenji Mouri

**Comment by bitsper2nd** [comment]
> I rather not use a tool that was obtained by tricking the original developer, taking open source work, rebranding it, and released with less than half the feature set that is supposed to go into a package manager.

Do you even know what free and open-source means and how it works?

**Comment by Jogai** [comment]
> > I rather not use a tool that was obtained by tricking the original developer, taking open source work, rebranding it, and released with less than half the feature set that is supposed to go into a package manager.
> 
> Do you even know what free and open-source means and how it works?

Yes, but I like the spirit of open source, not the legal side. And I think MS is killing the spirit of open source in .net like this. Offtopc, so for more insight I recommend this blog: https://aaronstannard.com/new-rules-dotnet-oss/

**Comment by bitsper2nd** [comment]
Then its completely the opposite of killing. The spirit of open-source is thriving more than ever thanks to individuals, communities and corporations. Nanazip is one of millions examples. A fork of a well-known project called 7zip. The goal is to have a modern GUI. Its possible due to 7zip being free and open-source. Anyone can access the source code and make their own copy to use or modify. Nanazip did that. Its the spirit of open-source.

**Comment by Jogai** [comment]
I'm not talking about NanaZip. This project is indeed working like OS should. This rant is in response to winget.
