### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by SeriousHoax** [M2Team/NanaZip#8]
This app needs a dark theme that 7zip doesn't have.

**Comment by MouriNaruto** [comment]
In my reddit post https://www.reddit.com/r/Windows11/comments/pz4vu5/comment/heyj6it, I have said "I also want to modernize the UX with XAML Islands, Windows 11 control style, Mica material and keep the original 7-Zip flavor.". So the dark theme will be added in NanaZip 2.x series because Windows 11 control style have light theme and dark theme modes. (I think it's also necessary for implementing the accessibility support. I always think accessibility support is important for every projects.)

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have updated the roadmap, and hope make users less confused.

https://github.com/M2Team/NanaZip#development-roadmap

Kenji Mouri

**Comment by SeriousHoax** [comment]
I see. Thanks for further clarifying it. Good luck on your project :)

**Comment by MouriNaruto** [comment]
I think it's time to close the issue because I have clarify them.

Kenji Mouri

**Comment by lazerl0rd** [comment]
https://github.com/huanrenfeng/7zipDarkmode might be helpful as an inspiration and or method.

**Comment by SakuraNeko** [comment]
@lazerl0rd Thank you for your suggestion, we will make reference to it.

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@JohnnyWild89 , @Shomnipotence discussed in [#243](https://github.com/M2Team/NanaZip/discussions/243)).
- For more information, please read #274. Thank you.

> ## Dark theme (Win 10)
> <sup>Originally posted by **@JohnnyWild89** November 22, 2022</sup>
> Is it possible to enable a dark theme for Nana in win 10? Currently, it's like a white flashlight on my monitor when Nana window is open.
>
> > <sup>Originally posted by **@Shomnipotence** November 22, 2022</sup>
> > look at the road map
> > 
> > > <sup>Originally posted by **@JohnnyWild89** November 22, 2022</sup>
> > > Oh, I thought that's the thing
> > > 
> > >     Start modernizing the UI with XAML Islands with the Windows 11 control style, dark and light mode support.
> > 
> > > <sup>Originally posted by **@Shomnipotence** November 22, 2022</sup>
> > > so you may see it in 2023
> > 
> > > <sup>Originally posted by **@JohnnyWild89** November 22, 2022</sup>
> > > Oh, pretty long... But thanks anyway!

**Comment by AndromedaMelody** [comment]
- This comment is converted from @bigplayer-ai 's comment
- Sorry, original issue is only used for publishing information. Please discuss dark mode here. Thanks for your understanding.

> <sup>Originally posted by **@ bigplayer-ai** </sup>
> ![0C8B674F-7BA8-4930-BAFE-4E6BD25E5310](https://user-images.githubusercontent.com/57533055/224477181-1651832c-cdda-4ea6-a2fd-238edb89cadd.jpeg)

**Comment by AndromedaMelody** [comment]
Reply @bigplayer-ai: We won’t provide an extra option. If there is any progress, @MouriNaruto will release a new preview version directly.

**Comment by ikoshura** [comment]
I attempted to use the 7Zip Dark Mode created by Huan (https://github.com/huanrenfeng/7zipDarkmode), made minor modifications using Resource Hacker to change both the app icon and toolbar icon, and also to hide the menubar since it couldn't apply the dark mode. Afterward, I replaced the NanaZip.exe file within the NanaZip msixbundle.

![Screenshot 2023-08-28 004821](https://github.com/M2Team/NanaZip/assets/100127946/726ff543-1471-4ca1-a125-f4647f034558)

The end result was that I achieved a 7Zip dark mode appearance, complete with the NanaZip icon and capability to display the menu in the Windows 11 Context Menu.

i uploaded the exe file here : https://github.com/ikoshura/NanaZip-Darkmode

**Comment by modz2014** [comment]
I have undertaken the initial review of the task, and it has come to my attention that while some efforts have been made, a specific concern remains. It is imperative to acknowledge the presence of the menubar, which unfortunately contributes to an aesthetically unpleasing appearance. Furthermore, an observation regarding the size of the icons has been duly noted, indicating their excessive dimensions. In order to achieve a refined and professional outcome, it is recommended that alterations be made in these areas while preserving the existing menubar. Your attention to these details is greatly appreciated as we endeavor to attain an optimal visual presentation. @ikoshura

**Comment by gsirvine** [comment]
I haven no idea how this works but why not create a fully new menu bar using a different method of menu creation instead of the default win32. Just use the same links from the win32 version. I'm sure it's more complicated than that. But I see plenty of programs doing that somehow. Like mp3tag or Pazera Audio Extractor. Maybe those are closed source freeware projects idk. Just saying it's not impossible afaik.

![image](https://github.com/M2Team/NanaZip/assets/32781300/ee80ccea-e712-4172-b4ff-bd272e26cbef)

**Comment by win98se** [comment]
@gsirvine NanaZip [3.0](https://github.com/M2Team/NanaZip/releases/tag/3.0.996) ([3.5.996](https://github.com/M2Team/NanaZip/releases/tag/3.5.996) in Preview) is already out with dark mode support.
